### PR TITLE
No config (yet)

### PR DESCRIPTION
**Pull request by makyo**
bundleservice doesn't support the config.yaml argument yet

### CODE REVIEW

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/bundleservice-deb/9/
Test PASSed.

**Comment by bac** [comment]
:+1:

**Comment by makyo** [comment]
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/bundleservice-deb-merge

**Pull request merged**
